import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../../features/budget/domain/models/budget_profile.dart';
import '../../features/budget/domain/models/spending_kind.dart';
import '../../features/budget/domain/models/transaction_entry.dart';
import '../utils/currency_formatter.dart';
import '../utils/month_utils.dart';

/// Bank-style monthly account statement as PDF.
class TransactionPdfExport {
  TransactionPdfExport._();

  static Future<void> shareMonthStatement({
    required DateTime month,
    required List<TransactionEntry> items,
    BudgetProfile? profile,
  }) async {
    final m = MonthUtils.startOfMonth(month);
    final monthLabel = MonthUtils.formatMonthYear(m);
    final sorted = [...items]
      ..sort((a, b) => a.effectiveDate.compareTo(b.effectiveDate));

    double credits = 0;
    double debits = 0;
    for (final t in sorted) {
      if (t.isCredit) {
        credits += t.amount;
      } else {
        debits += t.amount;
      }
    }
    final net = credits - debits;

    final doc = pw.Document();

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (context) => [
          pw.Header(
            level: 0,
            child: pw.Text(
              'Kharcha — Account statement',
              style: pw.TextStyle(
                fontSize: 18,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
          ),
          pw.SizedBox(height: 6),
          pw.Text(
            'Statement period: $monthLabel',
            style: const pw.TextStyle(fontSize: 11),
          ),
          if (profile != null) ...[
            pw.SizedBox(height: 4),
            pw.Text(
              'Profile: ${profile.monthlyIncome.toStringAsFixed(0)} / month income (reference)',
              style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
            ),
          ],
          pw.SizedBox(height: 16),
          pw.Container(
            padding: const pw.EdgeInsets.all(10),
            decoration: pw.BoxDecoration(
              border: pw.Border.all(color: PdfColors.grey400),
              borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
            ),
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                _sumCol('Total credits', credits),
                _sumCol('Total debits', debits),
                _sumCol('Net (credits − debits)', net, emphasize: true),
              ],
            ),
          ),
          pw.SizedBox(height: 16),
          pw.Text(
            'Transactions (${sorted.length})',
            style: pw.TextStyle(
              fontSize: 12,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
          pw.SizedBox(height: 8),
          pw.Table(
            border: pw.TableBorder.all(color: PdfColors.grey300),
            columnWidths: {
              0: const pw.FixedColumnWidth(72),
              1: const pw.FixedColumnWidth(36),
              2: const pw.FlexColumnWidth(2.2),
              3: const pw.FlexColumnWidth(1.8),
              4: const pw.FixedColumnWidth(72),
            },
            children: [
              pw.TableRow(
                decoration: const pw.BoxDecoration(color: PdfColors.grey200),
                children: [
                  _cell('Date', header: true),
                  _cell('Type', header: true),
                  _cell('Description', header: true),
                  _cell('Category', header: true),
                  _cell('Amount', header: true),
                ],
              ),
              ...sorted.map((t) {
                final d = t.effectiveDate.toLocal();
                final dateStr =
                    '${d.day.toString().padLeft(2, '0')}/${d.month.toString().padLeft(2, '0')}/${d.year}';
                final type = t.isCredit ? 'CR' : 'DR';
                return pw.TableRow(
                  children: [
                    _cell(dateStr),
                    _cell(type),
                    _cell(t.title),
                    _cell(t.displayCategoryLine),
                    _cell(
                      '${t.isCredit ? '+' : '-'}${CurrencyFormatter.formatRupee(t.amount)}',
                    ),
                  ],
                );
              }),
            ],
          ),
          pw.SizedBox(height: 24),
          pw.Text(
            'Generated by Kharcha. Amounts in INR (₹).',
            style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600),
          ),
        ],
      ),
    );

    final bytes = await doc.save();
    await Printing.sharePdf(
      bytes: bytes,
      filename: 'kharcha_statement_${m.year}_${m.month.toString().padLeft(2, '0')}.pdf',
    );
  }

  /// Export with arbitrary period label, category breakdown, and effective dates.
  static Future<void> shareReport({
    required String periodLabel,
    required List<TransactionEntry> items,
    BudgetProfile? profile,
  }) async {
    final sorted = [...items]
      ..sort((a, b) => a.effectiveDate.compareTo(b.effectiveDate));

    double credits = 0;
    double debits = 0;
    double needs = 0;
    double wants = 0;
    double savings = 0;
    double otherDebit = 0;

    for (final t in sorted) {
      if (t.isCredit) {
        credits += t.amount;
      } else {
        debits += t.amount;
        final k = t.spendingKind;
        if (k == null) {
          otherDebit += t.amount;
        } else {
          switch (k) {
            case SpendingKind.need:
              needs += t.amount;
            case SpendingKind.want:
            case SpendingKind.other:
              wants += t.amount;
            case SpendingKind.saving:
              savings += t.amount;
          }
        }
      }
    }
    final net = credits - debits;

    final doc = pw.Document();

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (context) => [
          pw.Header(
            level: 0,
            child: pw.Text(
              'Kharcha — Financial report',
              style: pw.TextStyle(
                fontSize: 18,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
          ),
          pw.SizedBox(height: 6),
          pw.Text(
            'Period: $periodLabel',
            style: const pw.TextStyle(fontSize: 11),
          ),
          if (profile != null) ...[
            pw.SizedBox(height: 4),
            pw.Text(
              'Monthly income (reference): ${CurrencyFormatter.formatRupee(profile.monthlyIncome)}',
              style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
            ),
          ],
          pw.SizedBox(height: 16),
          pw.Container(
            padding: const pw.EdgeInsets.all(10),
            decoration: pw.BoxDecoration(
              border: pw.Border.all(color: PdfColors.grey400),
              borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
            ),
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                _sumCol('Total income', credits),
                _sumCol('Total expenses', debits),
                _sumCol('Net', net, emphasize: true),
              ],
            ),
          ),
          pw.SizedBox(height: 14),
          pw.Text(
            'Category breakdown (expenses)',
            style: pw.TextStyle(
              fontSize: 12,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
          pw.SizedBox(height: 6),
          pw.Text(
            'Needs: ${CurrencyFormatter.formatRupee(needs)} · '
            'Wants: ${CurrencyFormatter.formatRupee(wants)} · '
            'Savings: ${CurrencyFormatter.formatRupee(savings)}'
            '${otherDebit > 0.01 ? ' · Other: ${CurrencyFormatter.formatRupee(otherDebit)}' : ''}',
            style: const pw.TextStyle(fontSize: 9),
          ),
          pw.SizedBox(height: 16),
          pw.Text(
            'Transactions (${sorted.length})',
            style: pw.TextStyle(
              fontSize: 12,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
          pw.SizedBox(height: 8),
          pw.Table(
            border: pw.TableBorder.all(color: PdfColors.grey300),
            columnWidths: {
              0: const pw.FixedColumnWidth(72),
              1: const pw.FixedColumnWidth(36),
              2: const pw.FlexColumnWidth(2.2),
              3: const pw.FlexColumnWidth(1.8),
              4: const pw.FixedColumnWidth(72),
            },
            children: [
              pw.TableRow(
                decoration: const pw.BoxDecoration(color: PdfColors.grey200),
                children: [
                  _cell('Date', header: true),
                  _cell('Type', header: true),
                  _cell('Description', header: true),
                  _cell('Category', header: true),
                  _cell('Amount', header: true),
                ],
              ),
              ...sorted.map((t) {
                final d = t.effectiveDate.toLocal();
                final dateStr =
                    '${d.day.toString().padLeft(2, '0')}/${d.month.toString().padLeft(2, '0')}/${d.year}';
                final type = t.isCredit ? 'CR' : 'DR';
                return pw.TableRow(
                  children: [
                    _cell(dateStr),
                    _cell(type),
                    _cell(t.title),
                    _cell(t.displayCategoryLine),
                    _cell(
                      '${t.isCredit ? '+' : '-'}${CurrencyFormatter.formatRupee(t.amount)}',
                    ),
                  ],
                );
              }),
            ],
          ),
          pw.SizedBox(height: 24),
          pw.Text(
            'Generated by Kharcha. Amounts in INR (₹).',
            style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600),
          ),
        ],
      ),
    );

    final bytes = await doc.save();
    var safe = periodLabel.replaceAll(RegExp(r'[^\w\-]'), '_');
    if (safe.isEmpty) safe = 'export';
    await Printing.sharePdf(
      bytes: bytes,
      filename: 'kharcha_report_$safe.pdf',
    );
  }

  static pw.Widget _sumCol(String label, double value, {bool emphasize = false}) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          label,
          style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey700),
        ),
        pw.SizedBox(height: 4),
        pw.Text(
          CurrencyFormatter.formatRupee(value),
          style: pw.TextStyle(
            fontSize: emphasize ? 12 : 11,
            fontWeight:
                emphasize ? pw.FontWeight.bold : pw.FontWeight.normal,
          ),
        ),
      ],
    );
  }

  static pw.Widget _cell(String text, {bool header = false}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(6),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontSize: header ? 8 : 9,
          fontWeight: header ? pw.FontWeight.bold : pw.FontWeight.normal,
        ),
      ),
    );
  }
}
